// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TSProjectInfo } from "./project_info";
import type { TSWorkspaceFolderInfo } from "./workspace_folder";

export type ApiContract = { info: InfoEndpointDef, workspace_index: WorkspaceIndexEndpointDef, workspace_list: WorkspaceListEndpointDef, workspace_delete: WorkspaceDeleteEndpointDef, index: WorkspaceIndexEndpointDef, events: EventsEndpointDef, graph_initial: GraphInitialEndpointDef, graph_neighbors: GraphNeighborsEndpointDef, graph_search: GraphSearchEndpointDef, graph_stats: GraphStatsEndpointDef, context_exclusion: ContextExclusionEndpointDef, java_endpoints: JavaEndpointsEndpointDef, java_service_calls: JavaServiceCallsEndpointDef, endpoint_flow: EndpointFlowEndpointDef, };

/**
 * Represents a node in the call tree
 */
export type CallTreeNode = { method_fqn: string, method_name: string, class_name: string, file_path: string, start_line: number, end_line: number, depth: number, call_type: CallType, is_external: boolean, children: Array<CallTreeNode>, };

/**
 * Type of method call
 */
export type CallType = "Direct" | "Ambiguous" | "Interface" | "Abstract";

export type ContextExclusionBodyRequest = { project_path: string, patterns: Array<string>, };

export type ContextExclusionEndpointDef = { method: HttpMethod, path: "/api/project/context-exclusion", path_request: EmptyRequest, body_request: ContextExclusionBodyRequest, query_request: EmptyRequest, responses: ContextExclusionResponses, };

export type ContextExclusionResponses = { "200": ContextExclusionSuccessResponse, "400": StatusResponse, "404": StatusResponse, "500": StatusResponse, };

export type ContextExclusionSuccessResponse = { project_path: string, patterns: Array<string>, reindexing_triggered: boolean, };

export type DefinitionNodeProperties = { path: string, fqn: string, definition_type: string, start_line: number, primary_start_byte: bigint, primary_end_byte: bigint, total_locations: number, annotations: Array<JavaAnnotation>, };

export type DirectoryNodeProperties = { path: string, absolute_path: string, repository_name: string, };

export type EmptyRequest = null;

export type EndpointFlowEndpointDef = { method: HttpMethod, path: "/api/graph/endpoint-flow/{workspace_folder_path}/{project_path}/{endpoint_id}", path_request: EndpointFlowPathRequest, body_request: EmptyRequest, query_request: EndpointFlowQueryRequest, responses: EndpointFlowResponse, };

export type EndpointFlowPathRequest = { workspace_folder_path: string, project_path: string, endpoint_id: string, };

export type EndpointFlowQueryRequest = { max_depth: number | null, };

/**
 * Endpoint flow response
 */
export type EndpointFlowResponse = { endpoint_id: number, endpoint_http_method: string, endpoint_path: string, endpoint_full_path: string, root_method: MethodNode, call_tree: Array<CallTreeNode>, statistics: FlowStatistics, project_info: TSProjectInfo, };

export type EndpointFlowResponses = { "200": EndpointFlowResponse | null, "404": StatusResponse | null, "400": StatusResponse | null, "500": StatusResponse | null, };

export type EventsEndpointDef = { method: HttpMethod, path: "/api/events", path_request: EmptyRequest, body_request: EmptyRequest, query_request: EmptyRequest, responses: EventsResponses, };

export type EventsResponses = Record<string, never>;

export type FileNodeProperties = { path: string, absolute_path: string, repository_name: string, language: string, extension: string, };

/**
 * Flow statistics
 */
export type FlowStatistics = { total_methods: number, max_depth: number, direct_calls: number, ambiguous_calls: number, external_calls: number, has_recursive_calls: boolean, };

export type GraphInitialEndpointDef = { method: HttpMethod, path: "/api/graph/initial/{workspace_folder_path}/{project_path}", path_request: GraphInitialPathRequest, body_request: EmptyRequest, query_request: GraphInitialQueryRequest, responses: GraphInitialSuccessResponse, };

export type GraphInitialPathRequest = { workspace_folder_path: string, project_path: string, };

export type GraphInitialQueryRequest = { directory_limit: number | null, file_limit: number | null, definition_limit: number | null, imported_symbol_limit: number | null, };

export type GraphInitialResponses = { "200": GraphInitialSuccessResponse | null, "404": StatusResponse | null, "400": StatusResponse | null, "500": StatusResponse | null, };

export type GraphInitialSuccessResponse = { nodes: Array<TypedGraphNode>, relationships: Array<GraphRelationship>, project_info: TSProjectInfo, };

export type GraphNeighborsEndpointDef = { method: HttpMethod, path: "/api/graph/neighbors/{workspace_folder_path}/{project_path}/{node_type}/{node_id}", path_request: GraphNeighborsPathRequest, body_request: EmptyRequest, query_request: GraphNeighborsQueryRequest, responses: GraphNeighborsSuccessResponse, };

export type GraphNeighborsPathRequest = { workspace_folder_path: string, project_path: string, node_type: string, node_id: string, };

export type GraphNeighborsQueryRequest = { limit: number | null, };

export type GraphNeighborsResponses = { "200": GraphNeighborsSuccessResponse | null, "404": StatusResponse | null, "400": StatusResponse | null, "500": StatusResponse | null, };

export type GraphNeighborsSuccessResponse = { nodes: Array<TypedGraphNode>, relationships: Array<GraphRelationship>, project_info: TSProjectInfo, };

export type GraphNodeCountsResponse = { directory_count: number, file_count: number, definition_count: number, imported_symbol_count: number, };

export type GraphRelationship = { id: string, source: string, target: string, relationship_name: string, relationship_type: string, };

export type GraphRelationshipCountsResponse = { directory_relationships: number, file_relationships: number, definition_relationships: number, };

export type GraphSearchEndpointDef = { method: HttpMethod, path: "/api/graph/search/{workspace_folder_path}/{project_path}", path_request: GraphSearchPathRequest, body_request: EmptyRequest, query_request: GraphSearchQueryRequest, responses: GraphSearchSuccessResponse, };

export type GraphSearchPathRequest = { workspace_folder_path: string, project_path: string, };

export type GraphSearchQueryRequest = { search_term: string, limit: number | null, };

export type GraphSearchResponses = { "200": GraphSearchSuccessResponse | null, "404": StatusResponse | null, "400": StatusResponse | null, "500": StatusResponse | null, };

export type GraphSearchSuccessResponse = { nodes: Array<TypedGraphNode>, project_info: TSProjectInfo, };

export type GraphStatsEndpointDef = { method: HttpMethod, path: "/api/graph/stats/{workspace_folder_path}/{project_path}", path_request: GraphStatsPathRequest, body_request: EmptyRequest, query_request: EmptyRequest, responses: GraphStatsSuccessResponse, };

export type GraphStatsPathRequest = { workspace_folder_path: string, project_path: string, };

export type GraphStatsResponses = { "200": GraphStatsSuccessResponse | null, "404": StatusResponse | null, "400": StatusResponse | null, "500": StatusResponse | null, };

export type GraphStatsSuccessResponse = { total_nodes: number, total_relationships: number, node_counts: GraphNodeCountsResponse, relationship_counts: GraphRelationshipCountsResponse, project_info: TSProjectInfo, };

export type HttpMethod = "GET" | "POST" | "DELETE";

export type ImportedSymbolNodeProperties = { path: string, start_line: number, primary_start_byte: bigint, primary_end_byte: bigint, import_type: string, import_path: string, import_alias: string, };

export type InfoEndpointDef = { method: HttpMethod, path: "/api/info", path_request: EmptyRequest, body_request: EmptyRequest, query_request: EmptyRequest, responses: InfoResponses, };

export type InfoResponses = { "200": ServerInfoResponse, };

export type JavaAnnotation = { name: string, arguments: Array<JavaAnnotationArgument>, };

export type JavaAnnotationArgument = { name: string | null, value: string, };

/**
 * Represents a Java REST API endpoint extracted from the knowledge graph
 */
export type JavaEndpoint = { id: number, http_method: string, path: string, full_path: string, consumes: string | null, produces: string | null, description: string | null, deprecated: boolean, path_params_json: string | null, query_params_json: string | null, request_body_json: string | null, response_body_json: string | null, file_path: string, start_line: number, end_line: number, };

export type JavaEndpointsEndpointDef = { method: HttpMethod, path: "/api/graph/java-endpoints/{workspace_folder_path}/{project_path}", path_request: JavaEndpointsPathRequest, body_request: EmptyRequest, query_request: JavaEndpointsQueryRequest, responses: JavaEndpointsSuccessResponse, };

export type JavaEndpointsPathRequest = { workspace_folder_path: string, project_path: string, };

export type JavaEndpointsQueryRequest = { limit: number | null, };

export type JavaEndpointsResponses = { "200": JavaEndpointsSuccessResponse | null, "404": StatusResponse | null, "400": StatusResponse | null, "500": StatusResponse | null, };

export type JavaEndpointsSuccessResponse = { endpoints: Array<JavaEndpoint>, project_info: TSProjectInfo, };

/**
 * Represents a Java external service call (e.g., FeignClient, RestTemplate, WebClient)
 */
export type JavaServiceCall = { service_type: string, service_name: string, service_url: string, http_method: string, path: string, full_path: string, class_name: string, class_fqn: string, method_name: string, method_fqn: string, file_path: string, line_number: bigint, };

export type JavaServiceCallsEndpointDef = { method: HttpMethod, path: "/api/graph/java-service-calls/{workspace_folder_path}/{project_path}", path_request: JavaServiceCallsPathRequest, body_request: EmptyRequest, query_request: JavaServiceCallsQueryRequest, responses: JavaServiceCallsSuccessResponse, };

export type JavaServiceCallsPathRequest = { workspace_folder_path: string, project_path: string, };

export type JavaServiceCallsQueryRequest = { limit: number | null, };

export type JavaServiceCallsResponses = { "200": JavaServiceCallsSuccessResponse | null, "404": StatusResponse | null, "400": StatusResponse | null, "500": StatusResponse | null, };

export type JavaServiceCallsSuccessResponse = { service_calls: Array<JavaServiceCall>, project_info: TSProjectInfo, };

/**
 * Job types that can be processed by the queue system.
 *
 * Each job variant represents a different type of work that can be performed.
 * Jobs are routed to workspace-specific queues for sequential processing.
 */
export type Job = { "type": "IndexWorkspaceFolder", "data": { workspace_folder_path: string, priority: JobPriority, java_property_files: Array<string>, } } | { "type": "ReindexWorkspaceFolderWithWatchedFiles", "data": { workspace_folder_path: string, workspace_changes: Array<string>, priority: JobPriority, } } | { "type": "ReindexProjectFolderWithWatchedFiles", "data": { workspace_folder_path: string, project_folder_path: string, project_changes: Array<string>, priority: JobPriority, } };

export type JobInfo = { id: string, job: Job, created_at: string, started_at: string | null, completed_at: string | null, status: JobStatus, error: string | null, };

/**
 * Priority levels for job processing.
 *
 * Higher priority jobs can cancel existing lower priority jobs for the same workspace.
 * This ensures user-triggered or high-priority operations take precedence over background tasks.
 */
export type JobPriority = "Low" | "Normal" | "High";

export type JobStatus = "Pending" | "Running" | "Completed" | "Failed" | "Cancelled";

/**
 * Represents a method node in the call tree
 */
export type MethodNode = { fqn: string, name: string, file_path: string, start_line: number, end_line: number, };

export type ServerInfoResponse = { port: number, version: string, };

export type StatusResponse = { status: string, };

export type TypedGraphNode = { "node_type": "DirectoryNode", id: string, node_id: string, label: string, properties: DirectoryNodeProperties, } | { "node_type": "FileNode", id: string, node_id: string, label: string, properties: FileNodeProperties, } | { "node_type": "DefinitionNode", id: string, node_id: string, label: string, properties: DefinitionNodeProperties, } | { "node_type": "ImportedSymbolNode", id: string, node_id: string, label: string, properties: ImportedSymbolNodeProperties, };

export type WorkspaceDeleteBodyRequest = { workspace_folder_path: string, };

export type WorkspaceDeleteEndpointDef = { method: HttpMethod, path: "/api/workspace/delete", path_request: EmptyRequest, body_request: WorkspaceDeleteBodyRequest, query_request: EmptyRequest, responses: WorkspaceDeleteResponses, };

export type WorkspaceDeleteResponses = { "200": WorkspaceDeleteSuccessResponse, "400": StatusResponse, "404": StatusResponse, "500": StatusResponse, };

export type WorkspaceDeleteSuccessResponse = { workspace_folder_path: string, removed: boolean, };

export type WorkspaceIndexBodyRequest = { workspace_folder_path: string, 
/**
 * Java property files for resolving ${...} placeholders
 * Supports .properties, .yml/.yaml, and .json formats
 */
java_property_files: Array<string>, };

export type WorkspaceIndexEndpointDef = { method: HttpMethod, path: "/api/workspace/index", path_request: EmptyRequest, body_request: WorkspaceIndexBodyRequest, query_request: EmptyRequest, responses: WorkspaceIndexResponses, };

export type WorkspaceIndexResponses = { "200": TSWorkspaceFolderInfo, "400": StatusResponse, "500": StatusResponse, };

export type WorkspaceListEndpointDef = { method: HttpMethod, path: "/api/workspace/list", path_request: EmptyRequest, body_request: EmptyRequest, query_request: EmptyRequest, responses: WorkspaceListResponses, };

export type WorkspaceListResponses = { "200": WorkspaceListSuccessResponse, "500": StatusResponse, };

export type WorkspaceListSuccessResponse = { workspaces: Array<WorkspaceWithProjects>, };

export type WorkspaceWithProjects = { workspace_info: TSWorkspaceFolderInfo, projects: Array<TSProjectInfo>, };
