// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TSProjectInfo = { project_path: string, workspace_folder_path: string, project_hash: string, status: string, last_indexed_at: string | null, error_message: string | null, database_path: string, parquet_directory: string, };
