// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TSWorkspaceFolderInfo = { workspace_folder_path: string, data_directory_name: string, status: string, last_indexed_at: string | null, project_count: number, };
